name: project_arcore
version: 1.0.0+1
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.3
  arcore_flutter_plugin: ^0.0.11
  camera: ^0.8.1+5
  path_provider: ^2.0.2
  get: 4.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - resources/images/
  uses-material-design: true

